config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "top#index"
  resources :users, only: [:show, :edit, :update]
  resources :class_rooms, only: [:new, :create, :show, :edit, :update]
  resources :chats, only: [:create]
  delete 'destroy_chat/:id' => 'chats#destroy_chat'
  delete 'destroy' => 'users_classes#destroy'
  get '/search' => 'class_rooms#search'
  get '/entry/:id' => 'class_rooms#entry'
  get '/register/:id' => 'class_rooms#register'

end

app/models/chat.rb
class Chat < ActiveRecord::Base
  belongs_to :user
  belongs_to :class_room
  validates_presence_of :user_id, :text, :class_room_id
end

app/models/class_room.rb
class ClassRoom < ActiveRecord::Base
  belongs_to :department
  # has_many :users, through: :departments, source: :user
  # has_and_belongs_to_many :users
  has_many :users, through: :users_classes
  has_many :chats
  #ユーザーがとっている授業を取り出したいときはjoinメソッドをつかう
  #UsersClass.joins(:class_rooms)してuser.class_rooms
  has_many :users_classes

  validates_presence_of :name, :department_id
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :users
  has_many :class_rooms
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :department_key
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, authentication_keys: [:email, :department_key]

  belongs_to :department
  # has_many :class_rooms, through: :departments, source: :class_room
  # has_and_belongs_to_many :class_rooms
  has_many :class_rooms, through: :users_classes
  has_many :chats
  #ユーザーがとっている授業を取り出したいときはjoinメソッドをつかう
  #UsersClass.joins(:class_rooms)してuser.class_rooms
  has_many :users_classes
  before_validation :department_key_to_id, if: :has_department_key?
  has_attached_file :avatar, styles: {medium: "300*300>", thumb: "100*100>"}
  validates_attachment_content_type :avatar, content_type: %w(image/jpeg image/jpg image/png)

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    department_key = conditions.delete(:department_key)
    department_id = Department.where(key: department_key).first
    email = conditions.delete(:email)
    # devise認証を、複数項目に対応させる
    if department_id && email
      where(conditions).where(["department_id = :department_id AND email = :email",
        { department_id: department_id, email: email }]).first
    elsif conditions.has_key?(:confirmation_token)
      where(conditions).first
    else
      false
    end
  end

  def full_profile?
    nickname?
  end

  private
  def has_department_key?
    department_key.present?
  end

  def department_key_to_id
    department = Department.where(key: department_key).first_or_create
    self.department_id = department.id
  end


end

app/models/users_class.rb
class UsersClass < ActiveRecord::Base
  belongs_to :user
  belongs_to :class_room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_in) << :department_key
  devise_parameter_sanitizer.for(:sign_up) << :department_key
  devise_parameter_sanitizer.for(:account_update) << :department_key
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def create
    @chat = Chat.create(create_params)
    redirect_to :controller => 'class_rooms', :action => 'show', :id => params[:class_room_id]
  end

  def destroy_chat
    chat = Chat.find(id_params[:id])
    chat.destroy
    redirect_to :controller => "class_rooms", :action => "show", :id => chat.class_room.id
  end

  private
  def create_params
    # params.permit(:text, :class_room_id).merge(user_id: current_user.id)
    required_params = params.require(:chat).permit(:text).merge(user_id: current_user.id)
    params.permit(:class_room_id).merge(required_params)
  end

  def id_params
    params.permit(:id)
  end
end

app/controllers/class_rooms_controller.rb
class ClassRoomsController < ApplicationController
  def new
    @class_room = ClassRoom.new
  end

  def create
    @class_room = ClassRoom.create(create_params)
    UsersClass.create(user_id: current_user.id, class_room_id: @class_room.id)
  end

  def search
    @class_rooms = current_user.department.class_rooms.where('name LIKE(?)', "%#{params[:keyword]}%").limit(20)
  end

  def show
    @class_room = ClassRoom.find(id_params[:id])
    @chats = @class_room.chats.all.order('created_at DESC')
    @chat = Chat.new
  end

  def entry
    @class_room = ClassRoom.find(id_params[:id])
  end

  def register
    @class_room = ClassRoom.find(params[:id])
    UsersClass.where(user_id: current_user.id, class_room_id: @class_room.id).first_or_create
    redirect_to :action => "show", :id => @class_room.id
  end

  def edit
    @class_room = ClassRoom.find(id_params[:id])
  end

  def update
    @class_room = ClassRoom.find(id_params[:id])
    @class_room.update(update_params)
  end

  private
  def create_params
    params.require(:class_room).permit(:name, :detail).merge(department_id: current_user.department_id)
  end

  def search_params
    params.permit(:keyword)
  end

  def update_params
    params.require(:class_room).permit(:name, :detail)
  end

  def id_params
    params.permit(:id)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @user =current_user
  end
end

app/controllers/users_classes_controller.rb
class UsersClassesController < ApplicationController
  def destroy
    users_classes = UsersClass.where(user_id: current_user.id, class_room_id: params[:class_room_id])
    users_classes.each do |users_class|
      users_class.destroy
    end
    redirect_to :root
  end

  private
  def id_params
    params.permit(:id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if current_user.id == params[:id].to_i
      @user = User.find(params[:id])
    else
      redirect_to :root, alert: "エラーが起きました"
    end
#notificationでリダイレクトで飛べなかったときの処理を書こう
  end

  def edit
  end

  def update
    current_user.update(update_params)
  end

  private
  def update_params
    params.require(:user).permit(:nickname, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/class_rooms_helper.rb
module ClassRoomsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_classes_helper.rb
module UsersClassesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/class_rooms/_class_room.html.erb
<% @chats.each do |chat| %>
  <%= chat.user.nickname %><br/>
  「<%= chat.text %>」<br/>
  <% if user_signed_in? && current_user.id == chat.user_id %>
  <li>
    <%= link_to '削除', "/destroy_chat/#{chat.id}", :controller => "chats", method: :delete %>
  </li>
  <% else %>
  <% end %>
<% end %>

app/views/class_rooms/create.html.erb
<h2>新しいクラスチャットルームを作成しました！</h2>
<p>教室内にいる友達を誘ってみましょう！</p>
<%= link_to "ホームに戻る", root_path %>

app/views/class_rooms/edit.html.erb
<%= form_for(@class_room) do |f| %>
      <h3><span>Q</span><%= @class_room.name %></h3>
      <div class="field">
        <%= f.text_area :name, placeholder: "授業名/教授名の書き方でクラスルームの名前を変更してください", cols:"30", rows:"10", autofocus:"true", class:"form-control" %>
      </div>
      <div class="field">
        <%= f.text_area :detail, placeholder: "授業の概要を変更してください", cols:"30", rows:"10", autofocus:"true", class:"form-control" %>
      </div>
      <%= f.submit "変更する", class:"btn btn-primary withripple"%>
    <% end %>

app/views/class_rooms/entry.html.erb
  <h2><%= @class_room.name %></h2><br />
  <p><%= @class_room.detail %></p>

  <p>
  <%= link_to "この授業をマイクラスチャットルームに登録して、チャットルームに入る", "/register/#{@class_room.id}" %>
  </p>
  <p>
  <%= link_to "自分が取ってる授業とは違ったのでホームに戻る", root_path %>
  </p>

app/views/class_rooms/new.html.erb
<div>
  <div>
    <%= form_for(@class_room) do |f| %>
      <h3><span>Q</span><%= @department.class %></h3>
      <div class="field">
        <%= f.text_area :name, placeholder: "授業名/教授名の書き方でクラスルームを作ってください", cols:"30", rows:"10", autofocus:"true", class:"form-control" %>
      </div>
      <div class="field">
        <%= f.text_area :detail, placeholder: "授業の概要を教えてください", cols:"30", rows:"10", autofocus:"true", class:"form-control" %>
      </div>
      <%= f.submit "作成する", class:"btn btn-primary withripple"%>
    <% end %>
  </div>
</div>

app/views/class_rooms/search.html.erb
<%= form_tag('/search', method: :get) do %>
  <input name="keyword" placeholder="授業名で検索" type="text" value=""><button class="btn-search" title="検索" type="submit"><i class="icon-search"></i></button></input>
  <form accept-charset="utf-8" action="/" class="js-search-submit" method="get">
</form>
<% end %>

<h2>検索結果</h2>
  <% @class_rooms.each do |class_room| %>
    <li>
      <%= link_to "#{class_room.name}", "/entry/#{class_room.id}" %>
    </li>
    <!-- /:idとなっているルーティングはpathのルーティングができない。 -->
  <% end %>

app/views/class_rooms/show.html.erb
<div>
  <h2><%= @class_room.name %>のクラスチャットルーム</h2>
</div>
<div>
 <p>〜  <%= @class_room.detail %>  〜</p>
</div>
<div>
  <%= link_to 'クラス情報を編集する', edit_class_room_path(@class_room) %>
</div>

<div>
  <%= form_for(@chat) do |f| %>
    <%= f.text_field :text, placeholder: "何か言ってみましょう" %>
      <%= f.submit "発言する" %>
      <%= hidden_field_tag(:class_room_id, @class_room.id) %>
    <% end %>
    <!-- hidden属性を使って、class_room_idを取得 -->
</div>
<div>
  <h4><%= link_to 'ホームに戻る', root_path %>
<div>
  <%= render partial: "class_room", :collections=> @chats %>
</div>

app/views/class_rooms/update.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3>授業情報の編集が完了しました。</h3>
    <%= link_to "チャットルームに戻る", class_room_path(@class_room) %>
  </div>
</div>

app/views/common/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">くまトーーク！！！</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="nav_box">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav_text" %>
        </li>
        <li class="nav_box"><%= link_to "マイページ", user_path(current_user.id) %></li>
        <li class="nav_box"><%= link_to "プロフィール編集", edit_user_path(current_user.id) %></li>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/common/_login_logo.html.erb
<div>
  <h1 class="logo">くまトーーク！</h1>
  <small class="explanation">早大生のためのSNSきたる！</small>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KumaTalk</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value| %>
  <% key = "info" if key == "notice" %>
  <% key = "danger"  if key == "alert" %>
  <%= content_tag :div, value, class: "alert alert-#{key}" %>
<% end %>
<%= yield %>

</body>

</html>

app/views/top/index.html.erb
<%= render partial: 'common/header' %>

<body>
  <% unless current_user.full_profile? %>
    <h2>まずは、名前とプロフィール画像を設定しましょう！</h2>
    <p>「くまトーーク！！」は授業ごとに区切られたチャットルームで自由にお話できるサービスです！</p>
  <% else %>
  <div class="row">
      <div class="col-sm-12">
        <div class="search_box">
          <%= link_to 'クラスチャットルームを検索する', '/search', {class: 'btn btn-lg btn-success' } %></div>
        </div>
      </div>

      <div class="col-sm-12">
        <div class ="create_box">
          <%= link_to 'クラスチャットルームを作成する', 'class_rooms/new',  {class: 'btn btn-lg btn-info' } %>
        </div>
      </div>

  <div class="clearfix">
    <div class="main_content">
      <article>
        <h4>-<%= @user.nickname %>さんが登録しているクラスチャットルーム-</h4>
          <div class="btn-group-vertical">
          <% @user.class_rooms.each do |class_room| %>
              <li class="btn btn-default"><%= link_to "#{class_room.name}", class_room_path(class_room.id) %>
                <%= form_tag('/destroy', method: :delete, controller: :users_classes, :id => "class_room.id") do %>
                <%= hidden_field_tag(:class_room_id, class_room.id) %>
                <%= submit_tag("削除する") %>
                <% end %>
              </li>
          <% end %>
          </div>
      </article>
    </div>
  </div>
  <% end %>
</body>

app/views/users/edit.html.erb
<%= form_for current_user do |f| %>
  <h2>登録情報</h2>
    <div class="field">
    <%= f.text_field :nickname, placeholder: 'ニックネーム' %>
    </div>
    <br />
   <h2>プロフィール画像</h2>
   <div class="field">
    <%= f.file_field :avatar, placeholder: '画像アップロード' %></div>
    <div class="actions">
    <%= f.submit "Edit" %>
  </div>
<% end %>

app/views/users/show.html.erb
<%= @user.nickname %>さんのユーザーページです。
  <div class="image" style="background-image: url(<%= @user.avatar.url(:medium) %>);"></div>
<% if current_user.id == @user.id %>
  <%= link_to 'プロフィール編集', edit_user_path(current_user.id) %>
<p>cssファイルを実装してないのでまだ画像はでません！すんません！
<% end %>

app/views/users/update.html.erb
<div>
  <h3>プロフィールの編集が完了しました。</h3>
  <%= link_to "ホームに戻る", root_path %>